config/routes.rb
load File.expand_path('api_routes.rb', File.dirname(__FILE__))

# rubocop:disable Layout/ExtraSpacing
Zendesk::Application.routes.draw do
  root controller: :access, action: :dispatch_to_home

  resource :account_setup, controller: :account_setup, only: :show do
    member do
      get :state, format: 'json'
    end
  end

  resources :texts, module: :cms, as: :cms_texts, path: '/dynamic_content/items' do
    collection do
      get  :export
      get  :export_csv
      get  :import
      post :import_data
    end

    resources :variants, except: :index
  end

  get '/cms/search', controller: 'cms/search', action: :index

  resources :csv_exports do
    collection do
      get :search_stats
      get :hc_search_stats
    end
  end

  resource :getting_started, controller: :getting_started do
    member do
      post :invite_agents
      get  :test_ticket
    end
  end

  get '/robots', controller: :robots, action: :index, constraints: lambda { |req| req.format == :txt }

  %i[index email challenge ticket details].each do |action|
    match "/verification/#{action}/:token", controller: :verification, action: action, as: :"#{action}_token_verification", via: :all
  end
  post  '/verification/details', controller: :verification, action: :details

  match '/export/tickets/:token', controller: :export, action: :tickets, via: :all

  namespace :account do
    resources :payments

    get '/:id/ready', controller: :readiness_proxy, action: :ready

    resource :subscription, controller: :subscription do
      collection do
        get :sponsorship
      end

      member do
        post :upgrade_from_trial
      end
    end

    resource  :feature_boost, controller: :feature_boost
    resources :translations, only: [:index]
  end

  scope '/support/admin', controller: :admin, as: :admin do
    get :automations,                          action: :rule
    get 'automations/:id',                     action: :rule
    get :macros,                               action: :rule
    get 'macros/:id',                          action: :rule
    get 'modal/automations/:id/reorder',       action: :rule
    get 'modal/automations/reorder',           action: :rule
    get 'modal/macros/:id/reorder',            action: :rule
    get 'modal/macros/reorder',                action: :rule
    get 'modal/macros/settings',               action: :rule
    get 'modal/triggers/:id/reorder',          action: :rule
    get 'modal/triggers/reorder',              action: :rule
    get 'modal/views/:id/reorder',             action: :rule
    get 'modal/views/reorder',                 action: :rule
    get :slas,                                 action: :rule
    get :triggers,                             action: :rule
    get 'triggers/:id',                        action: :rule
    get 'triggers/:id/revisions',              action: :rule
    get 'triggers/:id/revisions/:revision_id', action: :rule
    get :views,                                action: :rule
    get 'views/:id',                           action: :rule

    get 'routing/attributes/:id/values/:value_id',              action: :routing
    get 'routing/attributes',                                   action: :routing
    get 'modal/routing/attributes/:id/values/:value_id/agents', action: :routing
    get 'modal/routing/attributes/:id/values/:value_id/delete', action: :routing
    get 'modal/routing/attributes/:id/delete',                  action: :routing
    get 'modal/routing/views/:id/update',                       action: :routing
    get 'modal/routing/view/update',                            action: :routing
    get 'modal/routing/settings/ticket_skills',                 action: :routing
  end

  resource :certificate_signing_request, controller: :certificate_signing_request, only: [] do
    member do
      post :generate
      post :cancel
    end
  end

  resources :external_email_credentials, only: :destroy do
    collection do
      get :oauth_start
      get :oauth_callback
    end
  end

  namespace :settings do
    resource :account, controller: :account do
      collection do
        get :audits
      end

      member do
        put  :update_address
        put  :update_branding
        post :preview_branding
        put  :update_account_owner
        put  :update_localization
        put  :update_benchmark
        put  :update_subdomain
        get  :invoice
      end
    end

    resource :channels
    resource :chat, controller: :chat, only: [:show, :create, :update]

    resource :credit_card, controller: :credit_card, only: :new do
      collection do
        get :upgrade_from_trial
      end

      member do
        get :callback
      end
    end

    resource :email, controller: :email, only: [:show, :update]

    resource :api, controller: :api do
      member do
        put :update_settings
      end
    end

    resources :api_tokens, only: [:create, :update, :destroy]

    resource :mobile_portal, controller: :mobile_portal, only: :show do
      member do
        put :update_settings
        put :update_displayed_settings
        put :update_analytics_settings
      end
    end

    resource :customers do
      member do
        put :update_settings
        put :update_satisfaction
      end
    end

    resource :agents do
      member do
        put :update_settings
      end
    end

    resource :tickets do
      member do
        put :update_settings
        put :update_ticket_sharing
      end
    end

    resource :extensions do
      member do
        post   :update_sugar_crm
        get    :salesforce_oauth_callback
        get    :connect_to_salesforce
        get    :edit_salesforce_object
        delete :remove_salesforce_object
        get    :edit_salesforce_fields
        delete :remove_crm
        get    :salesforce_related_fields
        post   :save_salesforce_object
        put    :update_salesforce
        post   :sort_salesforce_objects
        post   :update_ms_dynamics
        get    :edit_object_filter
        post   :save_object_filter
      end
    end

    resource :yammer_integration, controller: :yammer_integration do
      member do
        get :connect_to_yammer
      end
    end

    resource :export_configuration, controller: :export_configuration, only: [] do
      member do
        put  :update_whitelisted_domain
        put  :disable
        post :enable_request
      end
    end

    resource :slas, controller: :slas, only: :show

    resource :security, controller: :security, only: [:show, :update] do
      collection do
        post :enqueue_certificate_job
        post :disable_zendesk_provisioned_ssl
        post :transition_to_sni
        get  :ssl_provisioning_status
      end
    end

    resources :recipient_addresses, except: :index do
      collection do
        get :preview
        get :table
      end
    end
  end

  # Mobile SDK Configuration
  namespace :mobile do
    namespace :sdk do
      resources :apps, except: :show do
        collection do
          get :onboarding
          put :accept_tos
        end
      end

      resources :auths, except: :show do
        member do
          put :generate_secret
        end
      end
    end
  end

  post '/settings/extensions/update_salesforce', controller: 'settings/extensions', action: :update_salesforce

  namespace :zuora do
    resource :credit_card, controller: :credit_card do
      member do
        get :zendesk_iframe
      end
    end

    resource :invoice, controller: :invoice, only: [] do
      member do
        get :invoice_items
        get :invoices
      end
    end
  end

  resource :crm, controller: :crm do
    member do
      get :sync_user_info
      get :sync_ticket_info
    end
  end

  match '/accounts/extend', controller: 'account/payments', action: :index, via: :all
  match '/payments',        controller: 'account/payments', action: :index, via: :all

  get '/agent/start', controller: 'activate_trial', action: 'index'
  post '/agent/activate_trial/activate', controller: 'activate_trial', action: 'activate', format: 'json'
  get '/agent/activate_trial/wait', controller: 'activate_trial', action: 'wait'
  get '/agent/activate_trial/failed', controller: 'activate_trial', action: 'fail'
  get '/agent/activate_trial/state', controller: 'activate_trial', action: 'state', format: 'json'

  scope '/agent', controller: :lotus_bootstrap do
    get  :dashboard
    post :dashboard

    match '/versions',           action: :versions, via: :all
    match '/',                   action: :show,     via: [:get, :post],
      constraints: lambda { |request| request.query_parameters.key?('redirect') }
    match '/',                   action: :index,    via: [:get, :post]
    match '/tickets/:ticket_id', action: :ticket,   via: [:get, :post]
    match '/talk(/*path)',       action: :talk,     via: [:get, :post]
    match '/chat(/*path)',       action: :chat,     via: [:get, :post]
    match '/(*route)',           action: :show,     via: [:get, :post]
  end

  resources :tickets do
    collection do
      get :created
      put :bulk
      get :bulk_result
      get :requester_change
    end

    member do
      get :incidents
      get :jira_ticket_details
      get :print
    end
  end

  resource :merge, controller: 'tickets/merge' do
    member do
      get :result
    end
  end

  get '/audits/:id/email', controller: :audit_emails, action: :show

  resources :accounts do
    collection do
      get :reminder
      get :available
    end
  end

  resources :requests, controller: 'requests/portal'

  scope controller: :satisfaction_ratings do
    get   '/satisfaction/good_this_week', action: :good_this_week, as: :good_this_week_satisfaction
    get   '/satisfaction/bad_this_week', action: :bad_this_week, as: :bad_this_week_satisfaction
    get   '/requests/:ticket_id/satisfaction/new/:token', action: :new, constraints: { token: /\w+/ }, as: :new_ticket_satisfaction

app/helpers/tabs_helper.rb
# Defines helper methods to build the standard Zendesk tabbed UI components. Used like this:
#
#  <%= zd_tabs do %>
#    <%= zd_tab('Tab One') do %>
#      <%= render :partial => 'tab_one' %>
#    <% end %>
#    <%= zd_tab('Tab Two') do %>
#      <%= render :partial => 'tab_two' %>
#    <% end %>
#  <% end %>
#
# The DOM id will be generated from the tab title, i.e. in the above there will be #tab_one and #tab_two. This
# can be overridden by specifying an explicit :id argument, e.g. zd_tab('Tab Three', :id => 'tab_3')
#
module TabsHelper
  def zd_tabs(args = {}, &block)
    @container_tabs = []

    content = content_tag(:div, capture(&block), class: "tabs_canvas")
    content = content_tag(:div, content, class: "tabs_content")

    unless @container_tabs.empty?
      display = @container_tabs.size == 1 ? "hide" : ""
      content = content_tag(:div, class: "tab_links clearfix #{display}") do
        @container_tabs.collect do |tab|
          link_to(tab[:title], "##{tab[:id]}", data: { title_value: tab[:title] }, class: tab[:default] ? "current" : "")
        end.join_preserving_safety
      end + content
    end
    content_tag(:div, content, class: "#{args[:class] || 'tabbed_container'} narrow")
  end

  def zd_tab(title, options = {}, &block)
    tab = { id: (options[:id] || title_to_dom_id(title)), title: title }

    if @container_tabs.empty?
      options[:class] = options[:class] ? "#{options[:class]} default_tab" : "default_tab"
      tab[:default] = true
    end
    @container_tabs << tab

    content_tag(:div, '', id: tab[:id], class: options[:class], &block)
  end

  def title_to_dom_id(title)
    title.gsub(/\W/, '_').squeeze('_').downcase
  end

  def zd_yes_no_radio(form, property, options = {})
    true_value  = true
    false_value = false

    if form.is_a?(ActionView::Helpers::FormBuilder::PropertySetFormBuilderProxy)
      true_value  = "1"
      false_value = "0"
    end

    if options.delete(:swap_values)
      true_value, false_value = false_value, true_value
    end

    yes_options = {}
    no_options  = {}

    if toggle = options.delete(:toggles)
      yes_options['data-toggles-show'] = toggle
      no_options['data-toggles-hide']  = toggle
    end

    if toggle = options.delete(:anti_toggles)
      yes_options['data-toggles-hide'] = toggle
      no_options['data-toggles-show']  = toggle
    end

    if form.is_a?(ActionView::Helpers::FormBuilder::PropertySetFormBuilderProxy)
      yes_options[:id] = "account_settings_#{property}_#{true_value}"
      no_options[:id] = "account_settings_#{property}_#{false_value}"
      yes_label = label_tag(yes_options[:id], I18n.t('txt.admin.helpers.tab_helper.yes_option'), class: "radio")
      no_label  = label_tag(no_options[:id], I18n.t('txt.admin.helpers.tab_helper.no_option'), class: "radio")
    else
      scrubbed_property = property.to_s.chomp('?')
      yes_label = form.label("#{scrubbed_property}_#{true_value}", I18n.t('txt.admin.helpers.tab_helper.yes_option'), class: "radio")
      no_label  = form.label("#{scrubbed_property}_#{false_value}", I18n.t('txt.admin.helpers.tab_helper.no_option'), class: "radio")
    end

    content_tag(:div, class: "radio horizontal") do
      form.radio_button(property, true_value, options.merge(yes_options)) + yes_label
    end + content_tag(:div, class: "radio horizontal") do
      form.radio_button(property, false_value, options.merge(no_options)) + no_label
    end
  end

  def zd_enable_checkbox(form, property, label_text, options = {})
    label = if form.is_a?(ActionView::Helpers::FormBuilder::PropertySetFormBuilderProxy)
      checkbox_id = form.send(:prepare_id_name, property, {})[:id]
      label_tag(property, label_text, class: 'checkbox', for: checkbox_id)
    else
      form.label(property, label_text, class: 'checkbox')
    end

    content_tag(:div, class: "enable_checkbox") do
      form.check_box(property, options) + "\n" + label
    end
  end

  def zd_sub_setting(property, options = {}, &block)
    display = options.reverse_merge(show: true).delete(:show) ? "show" : "hide"
    content_tag(:div, class: "sub_setting #{display}", id: "sub_setting_#{property}", &block)
  end
end

app/views/layouts/tabs/_settings_tab.html.erb
<%= tab(:settings, I18n.t('txt.admin.views.layout.tabs._settings_tab.Settings_tab'), main_app.settings_account_path) do %>
  <ul class="menu-drop">

    <%- if current_user.is_admin? -%>
      <% @account_tab_title = current_user.is_account_owner? ? I18n.t('txt.admin.views.layouts.tabs._settings_tab.Setup_billing_look_and_feel') : I18n.t('txt.admin.views.layouts.tabs._settings_tab.setup_look_and_feel')%>
      <li data-menu-item-name="settings_account"><%= link_to I18n.t('txt.admin.views.layout.tabs._settings_tab.Account_tab'), main_app.settings_account_path, :title => @account_tab_title %></li>
      <li><%= link_to I18n.t('txt.admin.views.layout.tabs._settings_tab.Security_tab'), main_app.settings_security_path, :title => I18n.t('txt.admin.views.layouts.tabs._settings_tab.setur_security_encryption_and_access') %></li>
    <%- end -%>

    <%- if current_user.can?(:edit, Access::Settings::Extensions) -%>
      <li><%= link_to I18n.t('txt.admin.views.layout.tabs._settings_tab.Channels_tab'), main_app.settings_channels_path, :title => I18n.t('txt.admin.views.layouts.tabs._settings_tab.control_the_ways_in_which_you_communicate') %></li>
    <%- end -%>

    <%- if current_user.is_admin? -%>
      <li><%= link_to I18n.t('txt.admin.views.layout.tabs._settings_tab.Tickets_tab'), main_app.settings_tickets_path, :title => I18n.t('txt.admin.views.layouts.tabs._settings_tab.settings_for_displaying_tickets') %></li>
      <li><%= link_to I18n.t('txt.admin.views.layout.tabs._settings_tab.Agents_tab'), main_app.settings_agents_path, :title => I18n.t('txt.admin.views.layouts.tabs._settings_tab.Configure_agent_abilities_and_signatures') %></li>
      <li><%= link_to I18n.t('txt.admin.views.layout.tabs._settings_tab.End_users_tab'), main_app.settings_customers_path, :title => I18n.t('txt.admin.views.layouts.tabs._settings_tab.control_how_end_users_can_access_your_help_desk') %></li>
    <%- end -%>

    <%- if current_user.can?(:edit, Access::Settings::Extensions) -%>
      <li><%= link_to I18n.t('txt.admin.views.layout.tabs._settings_tab.Extensions_tab'), main_app.settings_extensions_path, :title => I18n.t('txt.admin.views.layouts.tabs._settings_tab.configure_widgets_targets_and_integrations') %></li>
    <%- end -%>

    <% if current_user.is_account_owner? && !current_account.is_sandbox? %>
      <% if current_account.subscription.signup_as_trial? && current_account.subscription.hub_account_id.nil? %>
        <li><%= link_to I18n.t('txt.admin.views.layouts.settings_tab.buy_now'), subscription_settings_path, :class => "warning"  %></li>
      <% elsif !current_account.subscription.is_sponsored? %>
        <li><%= link_to I18n.t('txt.admin.views.layouts.tabs._settings_tab.Subscription'), subscription_settings_path, :title => I18n.t('txt.admin.views.layouts.tabs._settings_tab.Configure_plan_type_and_size') %></li>
      <% end %>
    <% end %>
  </ul>
<% end %>

app/views/layouts/tabs/_views_tab.html.erb
<%= tab(:views, I18n.t('txt.admin.views.layout.tabs._views_tab.Views_tab'), main_app.tickets_path, :id => "views-drop-anchor") do %>
  <ul class="menu-drop" id="views-drop">
    <%= render_shared_views %>

    <% if (personal_view = render_personal_views).present? -%>
      <li class="drop-header"><%= I18n.t('txt.admin.views.layout.tabs._views_tab.my_views_tab') %></li>
      <%= personal_view -%>
    <% end -%>
  </ul>
  <script type="text/javascript" charset="utf-8">
    var ruleCounts = new DelayedRuleCounts({
      ticket_show_empty_views: <%= current_account.settings.ticket_show_empty_views? %>
    });

    $j("#views-drop-anchor").one('mouseover', function(){
      ruleCounts.newRulesDisplayed();
    });
  </script>
<% end %>