config/routes.rb
load File.expand_path('api_routes.rb', File.dirname(__FILE__))

# rubocop:disable Layout/ExtraSpacing
Zendesk::Application.routes.draw do
  root controller: :access, action: :dispatch_to_home

  resource :account_setup, controller: :account_setup, only: :show do
    member do
      get :state, format: 'json'
    end
  end

  resources :texts, module: :cms, as: :cms_texts, path: '/dynamic_content/items' do
    collection do
      get  :export
      get  :export_csv
      get  :import
      post :import_data
    end

    resources :variants, except: :index
  end

  get '/cms/search', controller: 'cms/search', action: :index

  resources :csv_exports do
    collection do
      get :search_stats
      get :hc_search_stats
    end
  end

  resource :getting_started, controller: :getting_started do
    member do
      post :invite_agents
      get  :test_ticket
    end
  end

  get '/robots', controller: :robots, action: :index, constraints: lambda { |req| req.format == :txt }

  %i[index email challenge ticket details].each do |action|
    match "/verification/#{action}/:token", controller: :verification, action: action, as: :"#{action}_token_verification", via: :all
  end
  post  '/verification/details', controller: :verification, action: :details

  match '/export/tickets/:token', controller: :export, action: :tickets, via: :all

  namespace :account do
    resources :payments

    get '/:id/ready', controller: :readiness_proxy, action: :ready

    resource :subscription, controller: :subscription do
      collection do
        get :sponsorship
      end

      member do
        post :upgrade_from_trial
      end
    end

    resource  :feature_boost, controller: :feature_boost
    resources :translations, only: [:index]
  end

  scope '/support/admin', controller: :admin, as: :admin do
    get :automations,                          action: :rule
    get 'automations/:id',                     action: :rule
    get :macros,                               action: :rule
    get 'macros/:id',                          action: :rule
    get 'modal/automations/:id/reorder',       action: :rule
    get 'modal/automations/reorder',           action: :rule
    get 'modal/macros/:id/reorder',            action: :rule
    get 'modal/macros/reorder',                action: :rule
    get 'modal/macros/settings',               action: :rule
    get 'modal/triggers/:id/reorder',          action: :rule
    get 'modal/triggers/reorder',              action: :rule
    get 'modal/views/:id/reorder',             action: :rule
    get 'modal/views/reorder',                 action: :rule
    get :slas,                                 action: :rule
    get :triggers,                             action: :rule
    get 'triggers/:id',                        action: :rule
    get 'triggers/:id/revisions',              action: :rule
    get 'triggers/:id/revisions/:revision_id', action: :rule
    get :views,                                action: :rule
    get 'views/:id',                           action: :rule

    get 'routing/attributes/:id/values/:value_id',              action: :routing
    get 'routing/attributes',                                   action: :routing
    get 'modal/routing/attributes/:id/values/:value_id/agents', action: :routing
    get 'modal/routing/attributes/:id/values/:value_id/delete', action: :routing
    get 'modal/routing/attributes/:id/delete',                  action: :routing
    get 'modal/routing/views/:id/update',                       action: :routing
    get 'modal/routing/view/update',                            action: :routing
    get 'modal/routing/settings/ticket_skills',                 action: :routing
  end

  resource :certificate_signing_request, controller: :certificate_signing_request, only: [] do
    member do
      post :generate
      post :cancel
    end
  end

  resources :external_email_credentials, only: :destroy do
    collection do
      get :oauth_start
      get :oauth_callback
    end
  end

  namespace :settings do
    resource :account, controller: :account do
      collection do
        get :audits
      end

      member do
        put  :update_address
        put  :update_branding
        post :preview_branding
        put  :update_account_owner
        put  :update_localization
        put  :update_benchmark
        put  :update_subdomain
        get  :invoice
      end
    end

    resource :channels
    resource :chat, controller: :chat, only: [:show, :create, :update]

    resource :credit_card, controller: :credit_card, only: :new do
      collection do
        get :upgrade_from_trial
      end

      member do
        get :callback
      end
    end

    resource :email, controller: :email, only: [:show, :update]

    resource :api, controller: :api do
      member do
        put :update_settings
      end
    end

    resources :api_tokens, only: [:create, :update, :destroy]

    resource :mobile_portal, controller: :mobile_portal, only: :show do
      member do
        put :update_settings
        put :update_displayed_settings
        put :update_analytics_settings
      end
    end

    resource :customers do
      member do
        put :update_settings
        put :update_satisfaction
      end
    end

    resource :agents do
      member do
        put :update_settings
      end
    end

    resource :tickets do
      member do
        put :update_settings
        put :update_ticket_sharing
      end
    end

    resource :extensions do
      member do
        post   :update_sugar_crm
        get    :salesforce_oauth_callback
        get    :connect_to_salesforce
        get    :edit_salesforce_object
        delete :remove_salesforce_object
        get    :edit_salesforce_fields
        delete :remove_crm
        get    :salesforce_related_fields
        post   :save_salesforce_object
        put    :update_salesforce
        post   :sort_salesforce_objects
        post   :update_ms_dynamics
        get    :edit_object_filter
        post   :save_object_filter
      end
    end

    resource :yammer_integration, controller: :yammer_integration do
      member do
        get :connect_to_yammer
      end
    end

    resource :export_configuration, controller: :export_configuration, only: [] do
      member do
        put  :update_whitelisted_domain
        put  :disable
        post :enable_request
      end
    end

    resource :slas, controller: :slas, only: :show

    resource :security, controller: :security, only: [:show, :update] do
      collection do
        post :enqueue_certificate_job
        post :disable_zendesk_provisioned_ssl
        post :transition_to_sni
        get  :ssl_provisioning_status
      end
    end

    resources :recipient_addresses, except: :index do
      collection do
        get :preview
        get :table
      end
    end
  end

  # Mobile SDK Configuration
  namespace :mobile do
    namespace :sdk do
      resources :apps, except: :show do
        collection do
          get :onboarding
          put :accept_tos
        end
      end

      resources :auths, except: :show do
        member do
          put :generate_secret
        end
      end
    end
  end

  post '/settings/extensions/update_salesforce', controller: 'settings/extensions', action: :update_salesforce

  namespace :zuora do
    resource :credit_card, controller: :credit_card do
      member do
        get :zendesk_iframe
      end
    end

    resource :invoice, controller: :invoice, only: [] do
      member do
        get :invoice_items
        get :invoices
      end
    end
  end

  resource :crm, controller: :crm do
    member do
      get :sync_user_info
      get :sync_ticket_info
    end
  end

  match '/accounts/extend', controller: 'account/payments', action: :index, via: :all
  match '/payments',        controller: 'account/payments', action: :index, via: :all

  get '/agent/start', controller: 'activate_trial', action: 'index'
  post '/agent/activate_trial/activate', controller: 'activate_trial', action: 'activate', format: 'json'
  get '/agent/activate_trial/wait', controller: 'activate_trial', action: 'wait'
  get '/agent/activate_trial/failed', controller: 'activate_trial', action: 'fail'
  get '/agent/activate_trial/state', controller: 'activate_trial', action: 'state', format: 'json'

  scope '/agent', controller: :lotus_bootstrap do
    get  :dashboard
    post :dashboard

    match '/versions',           action: :versions, via: :all
    match '/',                   action: :show,     via: [:get, :post],
      constraints: lambda { |request| request.query_parameters.key?('redirect') }
    match '/',                   action: :index,    via: [:get, :post]
    match '/tickets/:ticket_id', action: :ticket,   via: [:get, :post]
    match '/talk(/*path)',       action: :talk,     via: [:get, :post]
    match '/chat(/*path)',       action: :chat,     via: [:get, :post]
    match '/(*route)',           action: :show,     via: [:get, :post]
  end

  resources :tickets do
    collection do
      get :created
      put :bulk
      get :bulk_result
      get :requester_change
    end

    member do
      get :incidents
      get :jira_ticket_details
      get :print
    end
  end

  resource :merge, controller: 'tickets/merge' do
    member do
      get :result
    end
  end

  get '/audits/:id/email', controller: :audit_emails, action: :show

  resources :accounts do
    collection do
      get :reminder
      get :available
    end
  end

  resources :requests, controller: 'requests/portal'

  scope controller: :satisfaction_ratings do
    get   '/satisfaction/good_this_week', action: :good_this_week, as: :good_this_week_satisfaction
    get   '/satisfaction/bad_this_week', action: :bad_this_week, as: :bad_this_week_satisfaction
    get   '/requests/:ticket_id/satisfaction/new/:token', action: :new, constraints: { token: /\w+/ }, as: :new_ticket_satisfaction

app/controllers/api/mobile/sdk/settings_controller.rb
# Used by Mobile Support SDK 1.X boot process
# Mobile Core SDK uses `Api::Private::MobileSdk::SettingsController`
class Api::Mobile::Sdk::SettingsController < Api::Mobile::BaseController
  HC_API_ERRORS = [
    ZendeskAPI::Error::ClientError,
    ZendeskAPI::Error::RecordInvalid,
    ZendeskAPI::Error::NetworkError,
    ZendeskAPI::Error::RecordNotFound,
    SocketError,
    Timeout::Error,
    Errno::ECONNREFUSED,
    Errno::EHOSTDOWN,
    Errno::EHOSTUNREACH,
    Errno::ETIMEDOUT
  ].freeze
  LOCALES_ENDPOINT = '/hc/api/v2/locales.json'.freeze
  LOCALES_SERVICE_NAME = 'locales'.freeze

  before_action :allow_only_mobile_sdk_clients_access
  before_action :set_cache_control_header
  after_action :disable_session_set_cookie

  skip_before_action :require_agent!
  skip_before_action :authenticate_user
  # skip_before_action :ensure_proper_protocol

  allow_parameters :show, id: Parameters.string
  def show
    if mobile_sdk_app.settings.helpcenter_enabled
      mobile_sdk_app.help_center_settings = help_center_settings
    end

    render json: presenter.present(mobile_sdk_app)
  end

  protected

  def presenter
    @presenter ||= Api::Mobile::Sdk::SettingsPresenter.new(
      current_user, url_builder: self, params: params, session: session, request: request
    )
  end

  private

  def mobile_sdk_app
    @mobile_sdk_app ||= current_account.mobile_sdk_apps.find_by_identifier!(params[:id])
  end

  def help_center_settings
    found_locale = begin
      hc_languages = help_center_available_languages(help_center_locales)
      settle = Zendesk::I18n::LanguageSettlement.new(http_accept_language, hc_languages)
      settle.find_matching_zendesk_locale.try(:locale) || help_center_default_locale
    end
    {
      locale: found_locale.downcase
    }
  end

  def help_center_default_locale
    help_center_locales.first ||
    current_account.translation_locale.try(:locale).try(:downcase) ||
    'en-us'
  end

  def help_center_available_languages(locales)
    current_account.available_languages.select do |l|
      locales.include?(l.locale.downcase)
    end
  end

  def help_center_locales
    hc_locales = Rails.cache.read(cache_key)
    return hc_locales if hc_locales
    hc_locales = fetch_locales
    Rails.cache.write(cache_key, hc_locales, expires_in: 10.minutes) unless hc_locales == []
    hc_locales
  end

  def cache_key
    @cache_key ||= "#{current_account.id}/#{current_brand.subdomain}/#{LOCALES_ENDPOINT}"
  end

  def fetch_locales
    hc_locales = api_client.get(LOCALES_ENDPOINT).body
    hc_locales.values_at('default_locale', 'locales').flatten
  rescue Kragle::ResponseError => e
    Rails.logger.info "[Api::Mobile::Sdk::SettingsController] Failed to fetch locales from Help Center using the subdomain #{current_brand.subdomain} - #{e.message}"
    []
  end

  def api_client
    Kragle.new(LOCALES_SERVICE_NAME) do |conn|
      conn.url_prefix = "https://#{current_brand.subdomain}.#{Zendesk::Configuration['host']}"
      conn.headers['Accept'] = 'application/json'
    end
  end

  # Cache control will be used by Cloudflare to cache the Mobile SDK settings
  # payload.
  def set_cache_control_header
    if current_account.has_mobile_sdk_settings_cache_control_headers?
      expires_in(10.minutes, public: true)
    end
  end

  def prevent_missing_account_access
    unless current_account.is_serviceable?
      expires_in(10.minutes, public: true)
    end
  rescue NoMethodError
    expires_in(10.minutes, public: true)
  ensure
    super
  end
end

app/controllers/api/v2/internal/voice/settings_controller.rb
module Api
  module V2
    module Internal
      module Voice
        class SettingsController < Api::V2::Internal::BaseController
          include ::Voice::BillingHelper

          before_action :only_allow_voice_settings, only: :cleanup_legacy_settings

          allow_parameters :update, settings: Parameters.map(
            voice:                                    Parameters.boolean,
            voice_outbound_enabled:                   Parameters.boolean,
            voice_maximum_queue_size:                 Parameters.integer & Parameters.gte(0) & Parameters.lte(100),
            voice_maximum_queue_wait_time:            Parameters.integer & Parameters.gte(1) & Parameters.lte(60),
            voice_recordings_public:                  Parameters.boolean,
            voice_only_during_business_hours:         Parameters.boolean,
            voice_agent_wrap_up_after_calls:          Parameters.boolean,
            voice_agent_confirmation_when_forwarding: Parameters.boolean
          )
          def update
            # This interface is extracted from internal to public
            # if voice_settings_audit_display_right_user feature is enabled.
            head(:not_found)
          end

          allow_parameters :cleanup_legacy_settings, settings: Parameters.array(Parameters.string) | Parameters.string
          def cleanup_legacy_settings
            current_account.settings.where(name: params.require(:settings)).delete_all
            head :ok
          end

          allow_parameters :billing_periods, {}
          def billing_periods
            @periods = if current_account.subscription.invoicing? || current_account.zuora_managed?
              periods_with_invoice
            else
              periods_with_payments
            end

            render json: @periods
          end

          private

          def only_allow_voice_settings
            settings = params.require(:settings)
            settings = [settings] if settings.is_a?(String)
            head(:unprocessable_entity) if settings.any? { |s| s !~ /^voice_/ }
          end
        end
      end
    end
  end
end

app/controllers/api/v2/knowledge/settings_controller.rb
class Api::V2::Knowledge::SettingsController < Api::V2::BaseController
  before_action :require_agent!

  allow_parameters :show, {}
  def show
    if stale?(etag: etag)
      render json: presenter.present(current_account)
    end
  end

  private

  def etag
    [
      Arturo::Feature.last_updated_at,
      current_account.settings.pluck(:updated_at).max,
      current_account.subscription.try(:cache_key),
      current_account.feature_boost.try(:cache_key),
      current_account.cache_key
    ]
  end

  def presenter
    @presenter ||= Api::V2::Account::KnowledgeSettingsPresenter.new(
      current_user,
      url_builder: self
    )
  end
end

app/controllers/api/v2/voice/settings_controller.rb
module Api
  module V2
    module Voice
      class SettingsController < Api::V2::BaseController
        allow_parameters :update, settings: Parameters.map(
          voice:                                    Parameters.boolean,
          voice_outbound_enabled:                   Parameters.boolean,
          voice_maximum_queue_size:                 Parameters.integer & Parameters.gte(0) & Parameters.lte(300),
          voice_maximum_queue_wait_time:            Parameters.integer & Parameters.gte(1) & Parameters.lte(120),
          voice_recordings_public:                  Parameters.boolean,
          voice_only_during_business_hours:         Parameters.boolean,
          voice_agent_wrap_up_after_calls:          Parameters.boolean,
          voice_agent_confirmation_when_forwarding: Parameters.boolean
        )
        def update
          current_account.settings.set(params.require(:settings))
          if current_account.settings.save
            head :ok
          else
            head :unprocessable_entity
          end
        end
      end
    end
  end
end

app/controllers/settings/channels_controller.rb
class Settings::ChannelsController < Settings::BaseController
  include ::AllowedParameters

  skip_before_action :authorize_admin
  before_action :check_permissions
  ssl_allowed :all

  allow_parameters :show, {}
  def show
  end

  private

  def check_permissions
    grant_access current_user.can?(:edit, Access::Settings::Extensions)
  end
end

app/views/settings/extensions/_ms_dynamics.html.erb
<%= form_for(:account, :url => { :action => "update_ms_dynamics", :anchor => "crm" },
  :html => { :class => 'two_column', :id => 'ms_dynamics_form', "data-on-premise" => @account.ms_dynamics_integration.try(:on_premise?), :autocomplete => 'off' }) do |f| %>
  <div class="element_group">

    <div class="form_element">
      <% if current_account.ms_dynamics_integration.try(:configured?) && !current_account.ms_dynamics_integration.try(:new_record?) %>
        <span class='label'>Connected</span>
        <div class="form_field">
          <p><%= I18n.t("txt.admin.views.settings.extensions._ms_dynamics.connected") %></p>
        </div>
      <% else %>
        <span class='label'><%= I18n.t("txt.admin.views.settings.extensions._ms_dynamics.connect") %></span>
        <div class="form_field">
          <p><%= I18n.t("txt.admin.views.settings.extensions._ms_dynamics.zendesk_for_dynamics", :zendesk_for_dynamics_link => link_to(I18n.t("txt.admin.views.settings.extensions._ms_dynamics.zendesk_for_dynamics_link"), I18n.t("txt.contextual.references.ms_dynamics.url"), :target => "_blank")) %></p>
          <% if current_account.crm_integration.try(:configured?) %>
            <p class="warning">
              <%= I18n.t("txt.admin.views.settings.extensions._crm.warning") %>
            </p>
          <% end %>
        </div>
      <% end %>
    </div>

    <%= fields_for @account.ms_dynamics_integration || @account.build_ms_dynamics_integration(:active => true) do |r| %>
      <div class="form_element">
        <%= r.label :type_code, I18n.t("txt.admin.views.settings.extensions._ms_dynamics.type_code.label") %>
        <div class="form_field">
          <%= r.select :type_code, options_for_select([[I18n.t("txt.admin.views.settings.extensions._ms_dynamics.type_code.cloud"), 0], [I18n.t("txt.admin.views.settings.extensions._ms_dynamics.type_code.on_premise"), 1], [I18n.t("txt.admin.views.settings.extensions._ms_dynamics.type_code.ifd"), 2]], @account.ms_dynamics_integration.try(:type_code)) %>
        </div>
      </div>

      <div class="form_element">
        <%= r.label :web_service_address, I18n.t("txt.admin.views.settings.extensions._ms_dynamics.web_service_address.label") %>
        <div class="form_field">
          <%= r.text_field :web_service_address, :placeholder => "https://domain.server.com:8080" %>
          <p><%= I18n.t("txt.admin.views.settings.extensions._ms_dynamics.web_service_address.description") %></p>
        </div>
      </div>

      <div class="form_element">
        <%= r.label :server_address, I18n.t("txt.admin.views.settings.extensions._ms_dynamics.crm_server_address.label") %>
        <div class="form_field">
          <%= r.text_field :server_address %>
          <p class="ms_dynamics_on_premise ms_dynamics_on_ifd"><%= I18n.t("txt.admin.views.settings.extensions._ms_dynamics.crm_server_address.description.premise") %></p>
          <p class="ms_dynamics_on_cloud"><%= I18n.t("txt.admin.views.settings.extensions._ms_dynamics.crm_server_address.description.cloud") %></p>
        </div>
      </div>

      <div class="ms_dynamics_on_premise ms_dynamics_on_ifd">
        <div class="form_element">
          <%= r.label :additional_domains, I18n.t("txt.admin.views.settings.extensions._ms_dynamics.additional_domains.label") %>
          <div class="form_field">
            <%= r.text_field :additional_domains %>
            <p><%= I18n.t("txt.admin.views.settings.extensions._ms_dynamics.additional_domains.description") %></p>
          </div>
        </div>
      </div>

      <div class="ms_dynamics_on_premise ms_dynamics_on_ifd">
        <div class="form_element">
          <%= r.label :domain_name, I18n.t("txt.admin.views.settings.extensions._ms_dynamics.domain_name.label") %>
          <div class="form_field">
            <%= r.text_field :domain_name %>
            <p><%= I18n.t("txt.admin.views.settings.extensions._ms_dynamics.domain_name.description") %></p>
          </div>
        </div>
      </div>

      <%# user_id is not on our system %>
      <div class="form_element">
        <%= r.label :user_id, I18n.t("txt.admin.views.settings.extensions._ms_dynamics.username.label") %>
        <div class="form_field">
          <%= r.text_field :user_id %>
          <p><%= I18n.t("txt.admin.views.settings.extensions._ms_dynamics.username.description") %></p>
        </div>
      </div>

      <div class="form_element">
        <%= r.label :password, I18n.t("txt.admin.views.settings.extensions._ms_dynamics.password.label") %>
        <div class="form_field">
          <%= r.password_field :password, :autocomplete => 'off' %>
          <p><%= I18n.t("txt.admin.views.settings.extensions._ms_dynamics.password.description") %></p>
        </div>
      </div>

      <div class="form_element">
        <%= r.label :discovery_uri, I18n.t("txt.admin.views.settings.extensions._ms_dynamics.discovery_uri.label") %>
        <div class="form_field">
          <%= r.text_field :discovery_uri, :placeholder => "https://dev.crm.dynamics.com/XRMServices/2011/Discovery.svc" %>
          <p><%= I18n.t("txt.admin.views.settings.extensions._ms_dynamics.discovery_uri.description") %></p>
        </div>
      </div>

      <div class="form_element">
        <%= r.label :organization_name, I18n.t("txt.admin.views.settings.extensions._ms_dynamics.organization_name.label") %>
        <div class="form_field">
          <%= r.text_field :organization_name, value: r.object.send(:organization_name) %>
          <p><%= I18n.t("txt.admin.views.settings.extensions._ms_dynamics.organization_name.description") %></p>
        </div>
      </div>

      <div class="form_element">
        <%= r.label :organization_uri, I18n.t("txt.admin.views.settings.extensions._ms_dynamics.organization_uri.label") %>
        <div class="form_field">
          <%= r.text_field :organization_uri, :placeholder => "https://dev.crm.dynamics.com/XRMServices/2011/Organization.svc" %>
          <p><%= I18n.t("txt.admin.views.settings.extensions._ms_dynamics.organization_uri.description") %></p>
        </div>
      </div>

      <div class="form_element">
        <%= f.label :active, I18n.t("txt.admin.views.settings.extensions._ms_dynamics.active.label") %>
        <div class="form_field">
          <%= zd_enable_checkbox(r, :active, I18n.t("txt.admin.views.settings.extensions._ms_dynamics.active.enable")) %>
          <p><%= I18n.t("txt.admin.views.settings.extensions._ms_dynamics.active.description") %></p>
        </div>
      </div>
    <% end %>
  </div>
  <div class="actions">
    <%= remove_selected_crm_link %>
    <%= submit_tag(I18n.t('txt.admin.views.settings.extensions._sugar.Save_tab_label'), :class => "button save", :id => "settings_extensions_ms_dynamics_save_button") %>
  </div>
<% end %>

app/views/settings/extensions/_salesforce_configuration.html.erb
<table>
  <tr>
    <td id="salesforce_objects">
      <div id="add_object">
        <%= link_to I18n.t("txt.admin.views.settings.extensions._salesforce3.add_object"), edit_salesforce_object_settings_extensions_path, :class => "edit_salesforce_object" %>
      </div>

      <div class="clear"></div>

      <div id="salesforce_selected_objects">
        <%= salesforce_selected_objects %>
      </div>

      <% if current_account.salesforce_integration.configuration.objects.size > 1 %>
        <div class="item reorder buttons-right">
          <%= link_to I18n.t('txt.admin.views.rules.index.reorder_label'), "#", id: "start_sorting" -%>
        </div>

        <%= render partial: "salesforce_selected_objects_sort" %>
      <% end %>

      <div class="clear"></div>
    </td>
    <td id="salesforce_test_app">
      <%= render partial: 'salesforce_test_app' %>
    </td>
  </tr>
</table>

app/views/settings/extensions/_salesforce_connection.html.erb
<div class="salesforce_connection <%= environment %>">
  <% if current_account.has_multiple_salesforce_connections? %>
    <%= salesforce_field.property_set(:settings).radio_button(:use_salesforce_production, setting, id: "use_salesforce_#{environment}") %>
  <% end %>
  <%= label_tag("use_salesforce_#{environment}", title, class: "radio") %>
  <% if is_configured %>
    <p><%= I18n.t('txt.admin.views.settings.extensions._salesforce_setup.Your_Zendesk_account_is_connected') %></p>
    <p><%= I18n.t('txt.admin.views.settings.extensions._salesforce_setup.Reconnect_to_Salesforce_to_reauthorize') %></p>
    <p><%= link_to I18n.t("txt.admin.views.settings.extensions._salesforce_setup.Click_here_to_reconnect"), connect_to_salesforce_settings_extensions_path(:salesforce_environment => environment), :target => "_top" %></p>
  <% else %>
    <p><%= link_to I18n.t("txt.admin.views.settings.extensions._salesforce_init.connect_to_salesforce"), connect_to_salesforce_settings_extensions_path(:salesforce_environment => environment), :class => "tracked", "data-tracking-module" => "CRM", "data-tracking-activity" => "Enabling salesforce.com", :target => "_top" %></p>
  <% end %>
</div>

app/views/settings/extensions/_salesforce_field.html.erb
<li class="ui-state-default field <%= field[:key].include?("::") ? "related" : "primary" %> <%= field[:select] ? "selected" : "non_selected" %>"
    data-field="<%= field[:key] %>"
    data-title="<%= field[:title] %>"
    data-type="<%= field[:type] %>">
  <span class="name"><%= field[:title] %></span>
  <% if field[:type] != "base64" # we can't use binary fields in SF queries %>
    <span class="add_link"><%= link_to I18n.t("txt.admin.views.settings.extensions._salesforce3.add_field"), "#" %></span>
  <% end %>
  <span class="remove_link"><%= link_to "X", "#" %></span>
</li>

app/views/settings/extensions/_salesforce_related_fields.html.erb
<ul class="related_sortable_fields">
  <% fields.each do |field| %>
    <%= render :partial => "salesforce_field", :locals => { :field => field } %>
  <% end %>
</ul>

app/views/settings/extensions/_salesforce_selected_objects_sort.html.erb
<div id="salesforce_selected_objects_sort" style="display:none">
  <ul id="salesforce_selected_objects_sort_list" class="rule-sorter sortablelist">
    <% current_account.salesforce_integration.configuration.objects.each_with_index do |object_name, i| -%>
      <li class="item sortable" id="item_<%= object_name %>" data-zendesk-original-position="<%= i -%>">
        <%= h(object_name) -%>
      </li>
    <% end -%>
  </ul>

  <div class="buttons-right">
    <%= link_to I18n.t('txt.admin.views.rules.sort.done_label'), "javascript:void(0);", id: "salesforce_selected_objects_reorder_done_link", class: "button" %>
    <%= link_to I18n.t('txt.admin.views.rules.sort.cancel_label'), "javascript:void(0);", id: "cancel_sorting" %>
    <div class="clear">&nbsp;</div>
  </div>
</div>

app/views/settings/extensions/_targets.html.erb
<p class="intro_text">
  <%= I18n.t('txt.admin.views.settings.extensions._targets.intro_text') %>  <%= learn_more(I18n.t('txt.admin.views.settings.extensions._targets.Learn_more'), :url => I18n.t('txt.admin.views.settings.extensions._targets.Learn_more_url')) %>
</p>

<div class="tab-top-right add-link">
  <p><%= link_to I18n.t('txt.admin.views.settings.extensions._targets.add_target'), '/targets/select_target_to_add', :class => 'add' %></p>
</div>

<div class="hover-actions item-border-top list-items">
  <h4><%= I18n.t('txt.admin.views.settings.extensions._targets.active_targets', :number_of_active_targets => @account.targets.active.count) %></h4>
  <%= render :partial => "target", :collection => @account.targets.active %>

  <% if @account.targets.inactive.any? %>
    <div class="setting-divider"></div>
    <div class="inactive">
      <h4><%= I18n.t('txt.admin.views.settings.extensions._targets.inactive_targets', :number_of_inactive_targets => @account.targets.inactive.count) %></h4>
      <%= render :partial => "target", :collection => @account.targets.inactive %>
    </div>
  <% end %>
</div>