config/routes.rb
load File.expand_path('api_routes.rb', File.dirname(__FILE__))

# rubocop:disable Layout/ExtraSpacing
Zendesk::Application.routes.draw do
  root controller: :access, action: :dispatch_to_home

  resource :account_setup, controller: :account_setup, only: :show do
    member do
      get :state, format: 'json'
    end
  end

  resources :texts, module: :cms, as: :cms_texts, path: '/dynamic_content/items' do
    collection do
      get  :export
      get  :export_csv
      get  :import
      post :import_data
    end

    resources :variants, except: :index
  end

  get '/cms/search', controller: 'cms/search', action: :index

  resources :csv_exports do
    collection do
      get :search_stats
      get :hc_search_stats
    end
  end

  resource :getting_started, controller: :getting_started do
    member do
      post :invite_agents
      get  :test_ticket
    end
  end

  get '/robots', controller: :robots, action: :index, constraints: lambda { |req| req.format == :txt }

  %i[index email challenge ticket details].each do |action|
    match "/verification/#{action}/:token", controller: :verification, action: action, as: :"#{action}_token_verification", via: :all
  end
  post  '/verification/details', controller: :verification, action: :details

  match '/export/tickets/:token', controller: :export, action: :tickets, via: :all

  namespace :account do
    resources :payments

    get '/:id/ready', controller: :readiness_proxy, action: :ready

    resource :subscription, controller: :subscription do
      collection do
        get :sponsorship
      end

      member do
        post :upgrade_from_trial
      end
    end

    resource  :feature_boost, controller: :feature_boost
    resources :translations, only: [:index]
  end

  scope '/support/admin', controller: :admin, as: :admin do
    get :automations,                          action: :rule
    get 'automations/:id',                     action: :rule
    get :macros,                               action: :rule
    get 'macros/:id',                          action: :rule
    get 'modal/automations/:id/reorder',       action: :rule
    get 'modal/automations/reorder',           action: :rule
    get 'modal/macros/:id/reorder',            action: :rule
    get 'modal/macros/reorder',                action: :rule
    get 'modal/macros/settings',               action: :rule
    get 'modal/triggers/:id/reorder',          action: :rule
    get 'modal/triggers/reorder',              action: :rule
    get 'modal/views/:id/reorder',             action: :rule
    get 'modal/views/reorder',                 action: :rule
    get :slas,                                 action: :rule
    get :triggers,                             action: :rule
    get 'triggers/:id',                        action: :rule
    get 'triggers/:id/revisions',              action: :rule
    get 'triggers/:id/revisions/:revision_id', action: :rule
    get :views,                                action: :rule
    get 'views/:id',                           action: :rule

    get 'routing/attributes/:id/values/:value_id',              action: :routing
    get 'routing/attributes',                                   action: :routing
    get 'modal/routing/attributes/:id/values/:value_id/agents', action: :routing
    get 'modal/routing/attributes/:id/values/:value_id/delete', action: :routing
    get 'modal/routing/attributes/:id/delete',                  action: :routing
    get 'modal/routing/views/:id/update',                       action: :routing
    get 'modal/routing/view/update',                            action: :routing
    get 'modal/routing/settings/ticket_skills',                 action: :routing
  end

  resource :certificate_signing_request, controller: :certificate_signing_request, only: [] do
    member do
      post :generate
      post :cancel
    end
  end

  resources :external_email_credentials, only: :destroy do
    collection do
      get :oauth_start
      get :oauth_callback
    end
  end

  namespace :settings do
    resource :account, controller: :account do
      collection do
        get :audits
      end

      member do
        put  :update_address
        put  :update_branding
        post :preview_branding
        put  :update_account_owner
        put  :update_localization
        put  :update_benchmark
        put  :update_subdomain
        get  :invoice
      end
    end

    resource :channels
    resource :chat, controller: :chat, only: [:show, :create, :update]

    resource :credit_card, controller: :credit_card, only: :new do
      collection do
        get :upgrade_from_trial
      end

      member do
        get :callback
      end
    end

    resource :email, controller: :email, only: [:show, :update]

    resource :api, controller: :api do
      member do
        put :update_settings
      end
    end

    resources :api_tokens, only: [:create, :update, :destroy]

    resource :mobile_portal, controller: :mobile_portal, only: :show do
      member do
        put :update_settings
        put :update_displayed_settings
        put :update_analytics_settings
      end
    end

    resource :customers do
      member do
        put :update_settings
        put :update_satisfaction
      end
    end

    resource :agents do
      member do
        put :update_settings
      end
    end

    resource :tickets do
      member do
        put :update_settings
        put :update_ticket_sharing
      end
    end

    resource :extensions do
      member do
        post   :update_sugar_crm
        get    :salesforce_oauth_callback
        get    :connect_to_salesforce
        get    :edit_salesforce_object
        delete :remove_salesforce_object
        get    :edit_salesforce_fields
        delete :remove_crm
        get    :salesforce_related_fields
        post   :save_salesforce_object
        put    :update_salesforce
        post   :sort_salesforce_objects
        post   :update_ms_dynamics
        get    :edit_object_filter
        post   :save_object_filter
      end
    end

    resource :yammer_integration, controller: :yammer_integration do
      member do
        get :connect_to_yammer
      end
    end

    resource :export_configuration, controller: :export_configuration, only: [] do
      member do
        put  :update_whitelisted_domain
        put  :disable
        post :enable_request
      end
    end

    resource :slas, controller: :slas, only: :show

    resource :security, controller: :security, only: [:show, :update] do
      collection do
        post :enqueue_certificate_job
        post :disable_zendesk_provisioned_ssl
        post :transition_to_sni
        get  :ssl_provisioning_status
      end
    end

    resources :recipient_addresses, except: :index do
      collection do
        get :preview
        get :table
      end
    end
  end

  # Mobile SDK Configuration
  namespace :mobile do
    namespace :sdk do
      resources :apps, except: :show do
        collection do
          get :onboarding
          put :accept_tos
        end
      end

      resources :auths, except: :show do
        member do
          put :generate_secret
        end
      end
    end
  end

  post '/settings/extensions/update_salesforce', controller: 'settings/extensions', action: :update_salesforce

  namespace :zuora do
    resource :credit_card, controller: :credit_card do
      member do
        get :zendesk_iframe
      end
    end

    resource :invoice, controller: :invoice, only: [] do
      member do
        get :invoice_items
        get :invoices
      end
    end
  end

  resource :crm, controller: :crm do
    member do
      get :sync_user_info
      get :sync_ticket_info
    end
  end

  match '/accounts/extend', controller: 'account/payments', action: :index, via: :all
  match '/payments',        controller: 'account/payments', action: :index, via: :all

  get '/agent/start', controller: 'activate_trial', action: 'index'
  post '/agent/activate_trial/activate', controller: 'activate_trial', action: 'activate', format: 'json'
  get '/agent/activate_trial/wait', controller: 'activate_trial', action: 'wait'
  get '/agent/activate_trial/failed', controller: 'activate_trial', action: 'fail'
  get '/agent/activate_trial/state', controller: 'activate_trial', action: 'state', format: 'json'

  scope '/agent', controller: :lotus_bootstrap do
    get  :dashboard
    post :dashboard

    match '/versions',           action: :versions, via: :all
    match '/',                   action: :show,     via: [:get, :post],
      constraints: lambda { |request| request.query_parameters.key?('redirect') }
    match '/',                   action: :index,    via: [:get, :post]
    match '/tickets/:ticket_id', action: :ticket,   via: [:get, :post]
    match '/talk(/*path)',       action: :talk,     via: [:get, :post]
    match '/chat(/*path)',       action: :chat,     via: [:get, :post]
    match '/(*route)',           action: :show,     via: [:get, :post]
  end

  resources :tickets do
    collection do
      get :created
      put :bulk
      get :bulk_result
      get :requester_change
    end

    member do
      get :incidents
      get :jira_ticket_details
      get :print
    end
  end

  resource :merge, controller: 'tickets/merge' do
    member do
      get :result
    end
  end

  get '/audits/:id/email', controller: :audit_emails, action: :show

  resources :accounts do
    collection do
      get :reminder
      get :available
    end
  end

  resources :requests, controller: 'requests/portal'

  scope controller: :satisfaction_ratings do
    get   '/satisfaction/good_this_week', action: :good_this_week, as: :good_this_week_satisfaction
    get   '/satisfaction/bad_this_week', action: :bad_this_week, as: :bad_this_week_satisfaction
    get   '/requests/:ticket_id/satisfaction/new/:token', action: :new, constraints: { token: /\w+/ }, as: :new_ticket_satisfaction

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include ::AllowedParameters
  include Zendesk::Home::ControllerSupport
  include Zendesk::SharedControllerSupport
  include HelpCenterRedirection

  deprecate_controller with_feature: :deprecate_home_controller

  allow_anonymous_access_to_public_forums

  # This method is a helper method such that we do not need to lookup entries that are only used inside a cache block
  helper_method :find_pinned_entries

  layout :layout_for_role

  cache_index_action

  allow_parameters :index,
    force_classic_layout: Parameters.string,  # config/initializers/schmobile.rb
    is_mobile:            Parameters.string,  # same
    show_version:         Parameters.boolean, # application_controller.rb
    challenge:            Parameters.string   # test/integration/authentication_test.rb

  # We are on the "home" page for an account, ie. /portal or /entries
  def index
    set_source_page
    self.tab    = :home
    @forums     = current_user.accessible_forums
    @categories = current_account.categories.all

    respond_to do |format|
      format.html
      format.rss { render action: 'index', formats: [:xml], layout: false }
    end
  end

  private

  def authenticate_user
    if should_redirect_to_help_center?
      redirect_to help_center_root_path
    else
      super
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def new_request_link
    link_to(I18n.t('txt.suggestions.deflect.submit_ticket'), appropiate_new_request_path)
  end

  def appropiate_new_request_path
    if current_account.is_open? && current_user.is_anonymous_user?
      main_app.new_anonymous_request_path
    else
      main_app.new_request_path
    end
  end

  def show_introductory_text?
    current_account.settings.show_introductory_text?
  end

  def account_introductory_title(edit_mode = false)
    intro_title = edit_mode ? current_account.introductory_title : Zendesk::Liquid::DcContext.render(current_account.introductory_title, current_account, current_user, nil, I18n.translation_locale)
    intro_title || default_introductory_title
  end

  def account_introductory_text(edit_mode = false)
    safe_text = current_account.introductory_text.to_s
    intro_text = edit_mode ? CGI.escape_html(safe_text) : Zendesk::Liquid::DcContext.render(safe_text, current_account, current_user, nil, I18n.translation_locale)
    (intro_text.presence || default_introductory_text).html_safe
  end

  def default_introductory_title
    I18n.t("txt.default.introductory_text.title", account_name: current_account.name, locale: current_account.translation_locale)
  end

  def default_introductory_text
    text =  I18n.t("txt.default.introductory_text.paragraph1", locale: current_account.translation_locale)
    text << tag(:br)
    text << I18n.t("txt.default.introductory_text.paragraph2", contact_us_link: mail_to(current_account.reply_address), locale: current_account.translation_locale)
  end
end

app/views/home/_csr_dashboard.html.erb
<div id="csr-dashboard">

  <div class="picture">
    <%= link_to edit_user_path(current_user, :anchor => "photo") do %>
      <img src="<%= photo_path(current_user) %>"/>
      <% if current_user.photo.nil? %>
        <p class="upload-link"><%= I18n.t('txt.admin.views.home._default_dashboard.upload_picture') %></p>
      <% end %>
    <% end %>
  </div>

  <div class="current-user">
    <h2><%= link_to current_user.name, user_path(current_user) %></h2>

    <%= render :partial => 'shared/csr_data_boxes', :locals => { :user => current_user } %>

  </div>
  <div class="clear"></div>
</div>

app/views/home/_dashboard.html.erb
<%= div_content do %>
  <% if current_account.has_customer_satisfaction_enabled? %>
    <%= render :partial => 'csr_dashboard' %>
  <% else %>
    <%= render :partial => 'default_dashboard' %>
  <% end %>
<% end %>

<%= render :partial => 'shared/safe_rules_search', :locals => { :anchor_selector => '.dashboard_search_link' } %>

app/views/home/_default_dashboard.html.erb
<div id="default-dashboard">
  <div class="content-top-right">
     <%= link_to_unless(
         user_open_ticket.zero?,
         render_dashboard_stats(
            user_open_ticket,
            I18n.t('txt.admin.views.home._default_dashboard.open_tickets_assigned_to_you_label'),
            I18n.t('txt.admin.views.home._default_dashboard.open_tickets_assigned_to_you_label_2'),
            'large'
         ),
         search_rules_path(
            :filter => 'views',
            :sets => build_set([assignee_condition(current_user), open_condition ]),
            :search_name => "Open tickets assigned to you",
            :authenticity_token => form_authenticity_token
         ),
         :class => "dashboard_search_link"
     ) %>
     <%= link_to_unless(
         new_and_open_tickets_in_group_with_restrictions.zero?,
         render_dashboard_stats(
            new_and_open_tickets_in_group_with_restrictions,
            I18n.t('txt.admin.views.home._default_dashboard.open_tickets_assigned_to_your_group_label'),
            I18n.t('txt.admin.views.home._default_dashboard.open_tickets_assigned_to_your_group_label_2'),
            'large'
         ),
         search_rules_path(
            :filter => 'views',
            :sets => build_set([users_groups, new_and_open_condition,  build_condition("is_not", nil, "group_id")]),
            :search_name =>"Open Tickets, in your group(s)",
            :authenticity_token => form_authenticity_token
         ),
         :class => "dashboard_search_link"
     ) %>
   </div>

  <div class="picture">
    <%= link_to edit_user_path(current_user, :anchor => "photo") do %>
      <img src="<%= photo_path(current_user) %>"/>
      <% if current_user.photo.nil? %>
        <p class="upload-link"><%= I18n.t('txt.admin.views.home._default_dashboard.upload_picture') %></p>
      <% end -%>
    <% end %>
  </div>

  <div class="current-user">
    <h2><%= link_to current_user.name, user_path(current_user) %></h2>
    <div class="agent-stats">
      <h3><%= I18n.t('txt.admin.views.home._default_dashboard.Your_ticket_stats_this_week')%></h3>
      <ul>
        <li><%= I18n.t('txt.admin.views.home._default_dashboard.number_of_tickets_solved_by_you', :number_of_tickets_solved => current_user.tickets_solved_this_week)%></li>
      </ul>
    </div>
  </div>

  <div class="clear"></div>
</div>

app/views/home/_introductory_text.html.erb
<div id="introductory_text">
  <%= div_content('green') do %>
    <div class="introductory_text_form" >
      <% if current_user.is_admin? %>
        <%= form_for :account, :url => { :controller => "settings/portal", :action => "update_intro_texts" }, :html => {:method => :put } do |f| -%>
          <p><%= f.text_field :introductory_title, :size => 50, :value => account_introductory_title(true) %></p>
          <p><%= f.text_area :introductory_text, :rows => 5, :cols => 60, :value => account_introductory_text(true) %>
          </p>
          <%= f.submit I18n.t('txt.admin.views.home._introductory_text.Save') %>
          <%= link_to I18n.t('txt.admin.views.home._introductory_text.Cancel'), "#", :class => "cancel_link" %>
        <% end %>
      <% end %>
    </div>

    <div class="introductory_display_texts">
      <% if current_user.is_admin? %>
        <div class="content-top-right">
          <p>
          <%= link_to I18n.t('txt.admin.views.home._introductory_text.edit'), "#", :class => "edit_this" %>
          </p>
        </div>
      <% end %>
      <h2><%= account_introductory_title %></h2>
      <p><%= account_introductory_text %></p>
    </div>
  <% end %>
</div>

app/views/home/_reorder_pinned_entries.html.mustache.erb
<div id="pinned_entries_reorderer">
  <div class='ordered pinned_entries_container'>
    <p>
      <%= I18n.t('txt.admin.views.home._reorder_pinned_entries.the_following_topics_will_always_be_presented') %>
    </p>
    <ol id='ordered_pinned_entries'>
      {{#orderedEntries}}
      <li id='pinned_entry_{{id}}' class='item sortable'>{{title}}</li>
      {{/orderedEntries}}
    </ol>
  </div>

  <div class='unordered pinned_entries_container'>
    <p>
      <%= I18n.t('txt.admin.views.home._reorder_pinned_entries.the_remainder_will_be_shown') %>
    </p>
    <ul id='unordered_pinned_entries'>
      {{#unorderedEntries}}
      <li id='pinned_entry_{{id}}' class='item sortable'>{{title}}</li>
      {{/unorderedEntries}}
    </ul>
  </div>
</div>

app/views/home/_search_result_forums2.html.erb
<div id="topic_search_loading"></div>
<div id="topic_search" style="display:none;">
  <div class="frame" style="margin-top: 15px; padding-bottom: 20px;">
    <div id="topic_search_result"></div>
    <%= render :partial => 'forums/search_deflect' %>
    <div style="clear:both;"></div>
  </div>
</div>

app/views/home/index.html.erb
<% if current_user.is_admin? %>
  <%= div_content('green') do %>
    <p><%= t 'txt.admin.forums.home.user_portal_help' %></p>
  <% end %>
<% end %>

<% if show_introductory_text? %>
  <%= render :partial => 'introductory_text' -%>
<% end %>

<%= js_init -%>