config/routes.rb
      put :update_notes
      put :toggle_suspend
    end

    resources :users, controller: 'people/users'

    resources :requests, only: :index, controller: 'requests/organization' do
      collection do
        get :search
        get :sidebar_users
      end
    end
  end

  get '/organization_requests', controller: 'requests/organization', action: :index # getting hit as /organization_requests.rss

  resources :groups, controller: 'people/groups' do
    collection do
      get :search
    end

    resources :users, controller: 'people/users'
  end

  get '/groups/:id/confirm_delete', controller: 'people/groups', action: :confirm_delete

  resources :users, controller: 'people/users' do
    collection do
      put  :bulk
      get  :revert
      post :revert
      get  :edit_password
      get  :merge
      put  :merge_with_email
      put  :merge_with_winner
      post :find_or_create
      post :select_bulk_action
      get  :autocomplete
      get  :multivalue_autocomplete
    end

    member do
      get  :successful_twitter_auth
      get  :successful_facebook_auth
      get  :create_twitter_profile
      put  :choose_locale
      post :assume
      put  :update_notes
      post :update_number
      get  :verify
      post :resend_welcome_email
      post :merge_complete
      get  :profiles_with_the_same_phone_number
    end

    resources :user_identities, only: [:index, :new, :create, :destroy] do
      member do
        post :make_primary
      end
    end

    resources :photos

    resources :unverified_email_addresses, only: [:new, :create, :destroy] do
      member do
        get :resend_email
        get :manual_agent_verify
      end
    end

    resource :merge, controller: 'people/user_merge' do
      collection do
        get :autocomplete
      end
    end
  end

  match '/rules/count', controller: 'rules/count', action: :index, via: :all

  namespace :rules do
    resources :analysis, only: :index do
      member do
        get :show # user is 302 redirected back here
        post :show
      end
    end

    # Internal routing
    get  '/views/preview', controller: :views, action: :preview
    post '/views/new_from_search', controller: :views, action: :new

    resources :views, :triggers, :automations do
      collection do
        put    :sort
        delete :destroy_inactive
      end

      member do
        put :activate
      end
    end
  end

  resources :rules, except: :index do
    collection do
      match  'search', via: :all
      put    :sort
      delete :destroy_inactive
    end

    member do
      put :activate
    end

    resources :tickets, only: :index, controller: 'rules/tickets'
  end

  get '/rules', controller: :tickets, action: :index

  resources :photos
  resources :logos

  match '/proxy/direct', controller: :proxy, action: :direct, via: :all

  resources :attachments do
    member do
      get :download_landing
    end
  end

  get  '/attachments/token/:id', controller: :attachments, action: :token, as: :attachment_by_token
  post '/attachments/create.json', controller: :attachments, action: :create, format: 'json'
  get  '/attachments/show/:id', controller: :attachments, action: :show

  get '/attachment/:account_id/:attachment_token', as: :attachment_token, controller: :attachment_token, action: :show

  resources :reports do
    collection do
      match :preview, via: [:post, :put]
      get   :settings
      get   :feed
      get   :amline
      get   :insights
    end

    member do
      get :data
    end
  end

  resources :ticket_fields do
    collection do
      get  :select_field_to_add
      post :sort
    end

    member do
      put :activate
    end
  end

  resources :suspended_tickets do
    member do
      put  :recover
      post :bulk
      get  :assign_to_requester
    end
  end

  match '/targets/new/:id', controller: :targets, action: :new, via: :all
  match '/targets/test/:id', controller: :targets, action: :test_target, via: [:put, :post]
  # this is special for yammer target callbacks
  match '/targets/yammer_callback', controller: :targets, action: :yammer_callback, via: :all

  resources :targets do
    collection do
      get    :select_target_to_add
      delete :delete_inactive
    end

    member do
      post :activate
      post :deactivate
    end
  end

  post  '/watchings/create/:id', controller: :watchings, action: :create
  post  '/watchings/destroy/:id', controller: :watchings, action: :destroy
  match '/watchings/unsubscribe/:token', controller: :watchings, action: :unsubscribe, via: :all
  match '/watchings/unsubscribe_comments/:token', controller: :watchings, action: :unsubscribe_comments, via: :all
  resources :watchings

  namespace :twitter do
    resources :reviewed_tweets, only: [:index, :create]
  end

  match '/recordings/:ticket_id/:comment_id/:sid', controller: 'voice/recordings', action: :show, via: :all
  match '/v2/recordings/:call_id/:sid', controller: 'voice/recordings', action: :show, via: :all

  resources :sharing_agreements, only: [:create, :show, :update, :destroy] do
    collection do
      delete :destroy_inactive
    end

    member do
      get :jira_projects
    end
  end

  namespace :voyager do
    resources :voyager_exports, only: :create

    get '/download/:id', controller: :voyager_exports, action: :download
  end

  namespace :sharing do
    post   '/agreements/:uuid', controller: :agreements, action: :create
    put    '/agreements/:uuid', controller: :agreements, action: :update
    post   '/tickets/:uuid', controller: :tickets, action: :create
    put    '/tickets/:uuid', controller: :tickets, action: :update
    delete '/tickets/:uuid', controller: :tickets, action: :destroy
  end

  match '/requests/organization/search', controller: 'requests/organization', action: :search, via: :all
  match '/requests/organization/:id',    controller: 'requests/organization', action: :index,  via: :all

  # Enable e.g. /tickets/315/events?filter=comments
  resources :tickets

  resources :entries, only: :show
  resources :forums, only: :show
  resources :categories, only: :show

  resources :survey, only: [:show, :create]

  match '/clientaccesspolicy.xml', controller: 'api/v2/integrations/ms_dynamics_policy', action: :index, via: :all

  match '/generated/stylesheets/branding/:top_directory/:account_id/:account_updated_at',
    controller: 'generated/stylesheets', action: :branding, via: :all
  match '/generated/stylesheets/branding/mobile/:top_directory/:account_id/:account_updated_at',
    controller: 'generated/stylesheets', action: :mobile_branding, via: :all
  match '/generated/javascripts/locale/:top_directory/:id/:cache_key', controller: 'generated/javascripts', action: :locale, via: :all

  resource :ping, controller: :ping do
    match 'host',                action: :host, via: :all
    match 'redirect_to_account', action: :redirect_to_account, via: :all
    match 'remote_ip',           action: :remote_ip, via: :all
    match 'shards(/:shard_id)',  action: :shards, via: :all
  end
  get :version, controller: :ping, action: :version

  match '/zuora/callback/ping',        controller: 'zuora/callback', action: :ping,        via: :all
  match '/zuora/callback/callback',    controller: 'zuora/callback', action: :callback,    via: :all
  match '/zuora/callback/inline_sync', controller: 'zuora/callback', action: :inline_sync, via: :all

  match '/cassets/:id', controller: :assets, action: :show, constraints: {id: /.*/}, via: :all
  match '/favicons',    controller: :favicons, action: :show, via: :all
  match '/favicon.ico', controller: :favicons, action: :show, via: :all

  match '/access/request_oauth', controller: :access, action: :request_oauth, as: :request_oauth_access, via: :all

  get :access, controller: :access, action: :index # This should be `root` in the namespace but that changes the route name
  namespace :access do
    get  :login
    post :login
    put  :login
    post :normal_login
    post :unauthenticated
    get  :unauthenticated
    get  :logout
    get  :normal
    get  :request_two_factor
    get  :configure_two_factor
    get  :oauth
    post :oauth
    get  :return_to
    post :return_to
    post :saml
    get  'saml/login',          action: :saml, sso_redirection_strategy: 'saml'
    get  :jwt
    post :jwt
    get  :sso
    post :sso
    get  'master/:token',       action: :master
    post :oauth_mobile,         action: :oauth_mobile_login
    get  :google
    get  :gam
    get  :office_365
    post 'sdk/jwt',             action: :sdk_jwt
    post 'sdk/anonymous',       action: :sdk_anonymous
    post :google_play
    post :google_play_jwt
    get  :one_time_password
    post :token
    get  'access_token/:token', action: :access_token
    get  :sso_bypass
  end

  # previously used default routing
  match '/generated/javascripts/mobile_user.js', controller: 'generated/javascripts', action: :mobile_user, via: :all, format: 'js'
  match '/generated/javascripts/user.json',      controller: 'generated/javascripts', action: :user,        via: :all, format: 'json'
  match '/generated/javascripts/locale.js',      controller: 'generated/javascripts', action: :locale,      via: :all, format: 'js'

  post  '/suspended_tickets/bulk',               controller: :suspended_tickets,      action: :bulk
  match '/registration',                         controller: :registration,           action: :index,   via: :all
  post  '/tags/autotag',                         controller: :tags,                   action: :autotag
  match '/requests/anonymous/new',               controller: 'requests/anonymous',    action: :new,     via: :all
  match '/requests/portal/new',                  controller: 'requests/portal',       action: :new,     via: :all
  match '/requests/portal/index',                controller: 'requests/portal',       action: :index,   via: :all

  match '/voice/settings',                       controller: 'voice/settings',                          via: :all

app/models/fraud/report.rb
module Fraud
  class Report < ActiveRecord::Base
    self.table_name = 'fraud_reports'

    after_commit :notify_voice

    include CIA::Auditable

    audit_attribute :account_id,
      :user_id,
      :risk_score,
      :ip_address,
      :source_event,
      :raw_response

    belongs_to :account
    belongs_to :user

    attr_accessible :account,
      :user,
      :risk_score,
      :ip_address,
      :source_event,
      :raw_response

    default_scope { order('created_at ASC') }

    def source_event
      super.to_sym
    end

    private

    def notify_voice
      Voice::SendFraudReportJob.enqueue(account.id, risk_score || 0)
    end
  end
end

app/controllers/api/v2/reports_controller.rb
class Api::V2::ReportsController < Api::V2::BaseController
  include Zendesk::Reports::ControllerSupport

  # ### Reports
  # `GET /api/v2/reports/{id}/result.json`
  #
  # #### Allowed For
  #
  #  * Admins
  #  * Agents
  #
  # #### Using curl
  #
  # ```bash
  # curl https://{subdomain}.zendesk.com/api/v2/reports/{id}/result.json \
  #   -v -u {email_address}:{password}
  # ```
  #
  # #### Example Response
  #
  # ```http
  # Status: 200 OK
  #
  # { report data }
  #
  # Status: 202 Accepted
  # job has old data, returned
  # { old report data }
  #
  # Status: 202 Accepted
  # job started in the background, will be ready soon
  # { "message": "<current status>"}
  # ```
  allow_parameters :result, :skip # TODO: make stricter
  require_oauth_scopes :result, scopes: [:read], arturo: true
  def result
    status, data = report_result
    respond_to do |format|
      format.json { render json: data, status: status }
    end
  end
end

app/helpers/reports_helper.rb
require 'zendesk_voyager_api_client'

module ReportsHelper
  def extended_metrics_visible?
    current_account.extended_ticket_metrics_visible? && !current_account.settings.only_extended_metrics?
  end

  def xml_export_actions
    actions = []
    actions << link_to(I18n.t('txt.admin.helpers.reports_helper.request_file_label'), "/jobs/create?type=xml_export", method: :post)

    if has_feature?(:xml_export) && @latest_xml_export
      actions << link_to(I18n.t('txt.admin.helpers.reports_helper.latest_label'), @latest_xml_export.url(token: true, relative: true))
    end

    actions.join("<span class=\"delim\">|</span>").html_safe
  end

  def operator_mapping(item)
    return @operator_map[item[1]] unless item[0].index('ticket_fields_')
    return 'is_not' if item[1].upcase.index('NOT REGEXP')
    'is'
  end

  def user_xml_export_actions
    actions = []
    actions << link_to(I18n.t('txt.admin.helpers.reports_helper.request_file_label'), "/jobs/create?type=user_xml_export", method: :post)

    if has_feature?(:user_xml_export) && @latest_user_xml_export
      actions << link_to(I18n.t('txt.admin.helpers.reports_helper.latest_label'), @latest_user_xml_export.url(token: true, relative: true))
    end

    actions.join("<span class=\"delim\">|</span>").html_safe
  end

  def percentage(value)
    "#{(value * 100).round}%"
  rescue
    "0%"
  end

  def has_totals # rubocop:disable Naming/PredicateName
    !@totals.blank?
  end

  def to_total(key, value)
    @totals ||= {}
    @totals[key] = (@totals[key] || 0) + value.to_i
  end

  def total(key)
    @totals[key] || 0
  end

  # amCharts doesn't show correctly legend names with '<'
  def legend_name(name)
    name.gsub(/</, '&lt;')
  end

  def report_options(report)
    options = if report.new_record?
      ['preview_report', 'create_report']
    else
      ['preview_report', 'update_report', 'delete_report']
    end
    options.map { |op| [translate_report_options_humanize(op), op] }
  end

  def translate_report_options_humanize(option)
    if option == 'preview_report'
      I18n.t('txt.admin.helpers.reports_helper.preview_report')
    elsif option == 'create_report'
      I18n.t('txt.admin.helpers.reports_helper.create_report')
    elsif option == 'delete_report'
      I18n.t('txt.admin.helpers.reports_helper.delete_report_label')
    elsif option == 'update_report'
      I18n.t('txt.admin.helpers.reports_helper.update_report_label')
    else
      option.humanize
    end
  end

  def get_gooddata_url # rubocop:disable Naming/AccessorMethodName
    I18n.t("txt.admin.views.reports.tabs.overview.learn_about_gooddata_zendesk_url")
  end

  def sparkline_containers(array)
    containers = ''
    array.each { |args| containers += sparkline_container(args) }
    containers.html_safe
  end

  def sparkline_container(args)
    content_tag(:div, class: 'sparkline_container search_sparkline_container') do
      content_tag(:div, class: 'sparkline_title') do
        I18n.t('txt.admin.helpers.reports_helper.sparkline_container', stats_total: content_tag(:span, '', class: 'stat_total'), stats_title: content_tag(:span, args[:title], class: 'stat_title'))
      end +
      content_tag(:div, class: 'search_sparkline', id: args[:id]) do
        content_tag(:div, '', id: "#{args[:id]}_sparkline", style: 'width:140px; height:18px;')
      end
    end
  end

  def export_intro_text
    show_json_export? ? I18n.t('txt.admin.views.reports.export.intro_text_with_json') : I18n.t('txt.admin.views.reports.export.intro_text')
  end

  def show_json_export?
    ::Arturo.feature_enabled_for?(:voyager_json_export, current_account)
  end

  def ranged_json_exports_enabled?
    ::Arturo.feature_enabled_for?(:voyager_ranged_json_exports, current_account)
  end

  def show_csv_export_history?
    ::Arturo.feature_enabled_for?(:voyager_csv_export_history, current_account)
  end

  def voyager_api_client
    @csv_export_client ||= Zendesk::VoyagerClientBuilder.build(current_account)
  end

  def successful_exports(type, per_page = 10)
    @successful_exports ||= {}
    @successful_exports[type] ||= begin
      result = voyager_api_client.list_exports(format_type: type, sort_order: 'DESC', per_page: per_page, state: 'finished')
      if result.successful? && !result.empty?
        result.exports
      else
        []
      end
    end
  end

  def last_export_time(type)
    @last_export_time ||= {}
    @last_export_time[type] ||= successful_exports(type).empty? ? 0 : successful_exports(type).map(&:end_time).sort.last
  end

  def voyager_export_url
    options = { metrics: !extended_metrics_visible? }
    voyager_voyager_exports_path(options)
  end
end

app/views/reports/_analytics_v2_sidebar.html.erb
<% if current_account.has_gooddata_advanced_analytics? %>
    <%= div_side_box(I18n.t('txt.admin.views.reports.sidebar.zendesk_insights')) do %>
        <% if action_name == 'index' %>
            <p><%= I18n.t('txt.admin.views.reports.sidebar.plus_enterprise_elegible_for_gooddata', :good_data_zendesk => "<a href=\"#{I18n.t('txt.admin.views.reports.export.good_data_zendesk_link')}\" target=\"_new\">#{I18n.t('txt.admin.views.reports.export.insights_zendesk_label')}</a>")%>
            </p>
            <ul class="options">
              <li><%= I18n.t('txt.admin.views.reports.sidebar.view_dashboard_prebuild_reports') %></li>
              <li><%= I18n.t('txt.admin.views.reports.sidebar.slice_dice_ticket') %></li>
              <li><%= I18n.t('txt.admin.views.reports.sidebar.daily_exports') %></li>
            </ul>
            <% if current_account.gooddata_integration && current_account.gooddata_integration.complete? %>
              <p><%= link_to content_tag(:strong, I18n.t('txt.admin.views.reports.sidebar.open_zendesk_insights_label')), insights_reports_path %></p>
            <% end %>
        <% end %>
    <% end %>
<% elsif current_account.subscription.plan_type == SubscriptionPlanType.Medium %>
    <%= div_side_box(I18n.t('txt.admin.views.reports.sidebar.zendesk_insights')) do %>
        <% if action_name == 'index' %>
            <p><%= I18n.t('txt.admin.views.reports.sidebar.plus_enterprise_elegible_for_gooddata', :good_data_zendesk => "<a href=\"#{I18n.t('txt.admin.views.reports.export.good_data_zendesk_link')}\" target=\"_new\">#{I18n.t('txt.admin.views.reports.export.insights_zendesk_label')}</a>")%></p>
            <p><%= link_to content_tag(:strong, I18n.t('txt.admin.views.reports.sidebar.updgrade_now_label')), subscription_settings_path %> <%= I18n.t('txt.admin.views.reports.sidebar.gain_ability_to')%></p>
            <ul class="options">
              <li><%= I18n.t('txt.admin.views.reports.sidebar.view_dashboard_prebuild_reports') %></li>
              <li><%= I18n.t('txt.admin.views.reports.sidebar.slice_dice_ticket') %></li>
              <li><%= I18n.t('txt.admin.views.reports.sidebar.daily_exports') %></li>
            </ul>
        <% end %>
    <% end %>
<% end %>

app/views/reports/_display_report.html.erb
<%= div_content(@is_preview? 'green' : 'grey') do %>

  <% if current_user.can?(:manage, Report) && !@is_preview %>
  <div class="content-top-right">
    <p>
        <%= link_to I18n.t('txt.admin.views.reports.display_report.csv_label'), "/reports/#{@report.id}.csv", :title => I18n.t('txt.admin.views.reports.display_report.report_data_in_csv_format') %>
       <span class="delim">|</span>
      <%= link_to I18n.t('txt.admin.views.reports.display_report.xml_label'), "/reports/#{@report.id}.xml", :target => "_blank", :title => I18n.t('txt.admin.views.reports.display_report.report_data_in_xml') %>
         <span class="delim">|</span>
      <%= link_to I18n.t('txt.admin.views.reports.display_report.edit_label'), edit_report_path(@report.id), { :class => 'edit_this' } %>
    </p>
  </div>
  <% end %>

  <div>
    <h2><%=
      if params[:action] == 'preview'
        I18n.t('txt.admin.controllers.reports_controler.preview_report_label', :report_title => ERB::Util.html_escape(@report.title))
      else
        h(@report.title)
      end
    %></h2>
    <div class="frame" style="padding-top:25px; padding-bottom:20px">

    <% legends = @report.table[:legends] %>

    <div style="text-align:center;margin-bottom:10px">
      <%= render :partial => "reports/am/display", :locals => { :report => @report, :legends => legends } %>
    </div>


    <% results = @report.table[:data] %>

    <table class="tickets" style="margin-top:20px">
      <thead>
        <tr>
          <th><%= I18n.t('txt.admin.views.reports.display_report.date_label') %></th>
          <% legends.each do |legend| %>
            <th><%= legend[:name] %></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% results.keys.sort.each do |key| %>
        <tr>
          <td><%= I18n.localize(key, :format => I18n.t("date.formats.short")) %></td>
          <% legends.each do |legend| %>
            <% value = (results[key][legend[:name]] || 0) %>
            <td><%= value %></td>
            <% to_total(legend[:name], value) if legend[:summable] %>
          <% end %>
        </tr>
        <% end %>
      </tbody>
      <% if has_totals %>
      <tfoot>
        <tr>
          <th><%= I18n.t('txt.admin.views.reports.display_report.total_label') %></th>
          <% legends.each do |legend| %>
            <th><%= legend[:summable] ? total(legend[:name]) : '&mdash;'.html_safe %></th>
          <% end %>
        </tr>
      </tfoot>
      <% end %>
    </table>

    </div>
  </div>

<% end %>

app/views/reports/edit.html.erb
<% @page_title = @report.new_record? ? I18n.t('txt.admin.views.reports.edit.add_new_report_label') : I18n.t('txt.admin.views.reports.edit.edit_report_label') %>
<% @operator_map = {
  '<' => 'less_than',
  '>' => 'greater_than',
  '>=' => 'greater_than',
  '=' => 'is', 'IS' => 'is',
  '!=' => 'is_not', 'IS NOT' => 'is_not',
  'REGEXP' => 'includes',
  'NOT REGEXP' => 'not_includes'
} %>
<%= render :partial => 'sidebar' %>

<%= js_init_with_escape %>

<%= div_content do %>

  <% content_for :script do %>
    <% context = Zendesk::Rules::Context.new(current_account, current_user, :rule_type => :report, :component_type => :condition, :condition_type => :all) %>
    reportConditionDefinitions = <%= ZendeskRules::Definitions::Conditions.definitions_as_json(context).to_json.gsub('/','\/').html_safe %>
    ruleEditingCapability = true;
    ruleActionEditingCapability = true;

    function addSeries() {
      if($j('#frames').children('.frame').length >= 8) {
        alert(I18n.t('txt.admin.views.reports.edit.error_max_8_data_series'));
        return;
      }

      var dataSeries = Zendesk.RuleUI.buildReportDataSeries(null, null, reportConditionDefinitions);
      $j('#frames').append(dataSeries.frame);
    }

    function submitReport() {
      action = $('submit_type').value;
      if(action == 'create_report' || action == 'update_report') {
        $('submit-button').value = I18n.t('txt.admin.views.reports.edit.submitting_label');
        $('submit-button').disabled = true;

        $('viewform').submit();
        return false;
      }
      else if(action == 'delete_report') {
        if(confirm(I18n.t('txt.admin.views.reports.edit.delete_this_report_label'))) {
          $('submit-button').value = I18n.t('txt.admin.views.reports.edit.deleteing_label');
          $('submit-button').disabled = true;
          $('deleteform').submit();
          return false;
        }
        else {
          return false;
        }
      }
      else if(action == 'preview_report') {

        new Ajax.Updater('preview-output', '/reports/preview/', {
          asynchronous:true, evalScripts:true, parameters:Form.serialize(document.viewform),
          onComplete:previewLoaded
        });

        $('submit-button').setAttribute('originalValue', $('submit-button').value);
        $('submit-button').value = I18n.t('txt.admin.views.reports.edit.previewing_label');
        $('submit-button').disabled = true;

        return false;
      }
      else {
        alert(I18n.t('txt.admin.views.reports.edit.invalid_action_notice'));
      }
    }

    function checkInterval() {
      if($('relative_radio').checked) {
        $('fixed_interval_selection').hide();
        $('relative_interval_selection').show();
      }
      else {
        $('fixed_interval_selection').show();
        $('relative_interval_selection').hide();
      }
    }

    function previewLoaded() {
        if($('submit-button') != null) {
          $('submit-button').value = $('submit-button').getAttribute('originalValue');
          $('submit-button').disabled = false;
        }
    }
  <% end %>

  <% content_for :head do %>
    <%= javascript_include_tag "new_rule" %>
  <% end %>

  <%= form_for @report,
              :html => { :name => 'viewform', :id => 'viewform',
              :onsubmit => 'return submitReport()' } do |f| %>
    <h2><%= I18n.t('txt.admin.views.reports.edit.report_title_label') %></h2>
    <%= f.text_field :title, :class => 'title' %>

    <h3><%= I18n.t('txt.admin.views.reports.edit.reporting_period_label') %></h3>
    <label class="option">
    <%= f.radio_button :is_relative_interval, true,  { :class => 'radio', :onclick => 'checkInterval()', :id => 'relative_radio' } %> <%= I18n.t('txt.admin.views.reports.edit.relative_to_today_label') %></label>
    <label class="option"><%= f.radio_button :is_relative_interval, false, { :class => 'radio', :onclick => 'checkInterval()' } %> <%= I18n.t('txt.admin.views.reports.edit.fixed_date_interval_label') %></label>
    <!--<p>Select how far back in time your report works, or specify a fixed period.</p>-->

    <div id="relative_interval_selection" class="indented_option" style="margin-top:15px; display:<%= @report.is_relative_interval? ? 'block' : 'none' %>">
      <!--<h3>Select period</h3>-->
      <%= f.select :relative_interval_in_days, [[I18n.t('txt.admin.views.reports.edit.last_week_label'), 7], [I18n.t('txt.admin.views.reports.edit.last_2_weeks_label'), 14], [I18n.t('txt.admin.views.reports.edit.last_month_label'), 30], [I18n.t('txt.admin.views.reports.edit.last_3_months_label'), 91]] %>
    </div>

    <div id="fixed_interval_selection" class="indented_option" style="margin-top:15px;display:<%= @report.is_relative_interval? ? 'none' : 'block' %>">
      <!--<h3>Select dates</h3>-->
      <%= f.date_select :from_date, :order => I18n.t('date.order').map(&:to_sym), :start_year => 2009, :end_year => Date.today.year, :default => 1.month.ago.to_date %> &nbsp;&nbsp;<%= I18n.t('txt.admin.views.reports.edit.to_label') %>&nbsp;&nbsp;
      <%= f.date_select :to_date, :order => I18n.t('date.order').map(&:to_sym), :start_year => 2009, :end_year => Date.today.year, :default => Date.today %>
    </div>

    <!-- Report series frames -->
    <h3><%= I18n.t('txt.admin.views.reports.edit.data_series_label') %></h3>
    <div id="frames"></div>

    <% @report.sets.sort{ |x,y| x[:legend][:name] <=> y[:legend][:name] }.each do |set| %>
      <% content_for :script_onload do %>
        var dataSeries = Zendesk.RuleUI.buildReportDataSeries('<%= escape_javascript(set[:legend][:name]).html_safe %>', '<%= set[:state] %>', reportConditionDefinitions);
        $j('#frames').append(dataSeries.frame);
        <% (set[:data] || []).each do |item| %>
          var source = '<%= item[0] %>';
          var operator = '<%= operator_mapping(item) %>';
          if (source.include("_within_business_hours")) {
            source = source.replace("_within_business_hours", "");
            operator = operator + "_business_hours";
          }
          dataSeries.addConditionRow(source, operator, <%= js_array(item[2]) %>);
        <% end %>
      <% end %>
    <% end %>

    <% if @report.sets.empty? %>
      <% content_for :script_onload do %>
        $j('#frames').append(Zendesk.RuleUI.buildReportDataSeries(null, null, reportConditionDefinitions).frame);
      <% end %>
    <% end %>

    <a href="#" style="float:left;" onclick="addSeries();return false;"><%= I18n.t('txt.admin.views.reports.edit.add_data_series_label')%></a>

    <div class="action">
      <%= select_tag 'submit_type', options_for_select(report_options(@report)), :style => 'font-weight:bold' %>
      <%= submit_tag I18n.t('txt.admin.views.reports.edit.submit_label'), :id => 'submit-button', :class => 'button primary' %>
    </div>

  <% end %>

<% end %>

<%= javascript_include_tag "swfobject" %>
<div id='preview-output'></div>

<% unless @report.new_record? %>
  <%= form_for :report, :url => report_path(@report.id),
              :html => { :id => 'deleteform', :method => :delete } do |f| %>
  <% end %>
<% end %>

app/views/reports/show.html.erb
<% @page_title = I18n.t('txt.admin.views.reports.index.reports_label') %>

<%= render :partial => 'sidebar' %>
<%= render :partial => 'display_report' %>